[package]
name = "icarus"
version = "0.2.0"
edition = "2024"

[dependencies]
axum = { version = "0.8.4", features = ["multipart"] }
serde = { version = "1.0.219", features = ["derive"] }
serde_json = { version = "1.0.140" }
tower = { version = "0.5.2" }
tokio = { version = "1.45.1", features = ["full"] }
tokio-util = { version = "0.7.15" }
tower-http = { version = "0.6.6", features = ["timeout"] }
tracing-subscriber = "0.3.19"
# mime = { version = "0.3.17" }
# mime_guess = { version = "2.0.5" }
futures = { version = "0.3.31" }
uuid = { version = "1.16.0", features = ["v4", "serde"] }
sqlx = { version = "0.8.5", features = ["postgres", "runtime-tokio-native-tls", "time", "uuid"] }
time = { version = "0.3.41", features = ["formatting", "macros", "parsing", "serde"]  }
icarus_meta = { git = "ssh://git@git.kundeng.us/phoenix/icarus_meta.git", tag = "v0.1.30" }
icarus_models = { git = "ssh://git@git.kundeng.us/phoenix/icarus_models.git", tag = "v0.4.3" }
icarus_envy = { git = "ssh://git@git.kundeng.us/phoenix/icarus_envy.git", tag = "v0.2.0" }

[dev-dependencies]
common-multipart-rfc7578 = { version = "0.7.0" }
url = { version = "2.5.4" }
tempfile = { version = "3.19.1" }
